networks:
  iot-server-net: {}

volumes:
 iot-server-net: {}

services:
  
  # iot-server:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   command: ['yarn', 'dev']
  #   depends_on:
  #     database:
  #       condition: service_healthy
  #   networks:
  #     - iot-server-net
  #   ports:
  #     - 3000:${PORT}/tcp
  #   volumes:
  #     - .:/iot-server
  
  database:
    image: timescale/timescaledb:latest-pg15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB -h localhost"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 20s
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=
    restart: unless-stopped
    ports:
      - 5432:${POSTGRES_DB_PORT}
    networks:
      - iot-server-net
    volumes:
      - iot-server-vol:/var/lib/pgsql

  adminer:
    image: adminer
    healthcheck:
      interval: 5s
      retries: 5
      start_period: 20s
      test: ['CMD', 'wget', '--no-verbose', '--spider', 'http://localhost:8080']
      timeout: 5s
    environment:
      - ADMINER_DEFAULT_SERVER=database
      - ADMINER_PLUGINS=dump-json dump-zip edit-foreign json-column tables-filter tinymce
    restart: always
    networks:
      - iot-server-net
    ports:
      - 8080:8080/tcp

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-server
    environment:
      - DB_SERVER_HOST=database
      - POSTGRES_DB=iot_platform
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
    depends_on:
      - database
    ports:
      - 10051:10051
    volumes:
      - ./zbx_env/alertscripts:/usr/lib/zabbix/alertscripts
      - ./zbx_env/externalscripts:/usr/lib/zabbix/externalscripts
    networks:
      - iot-server-net

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    container_name: zabbix-web
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - DB_SERVER_HOST=postgres
      - POSTGRES_DB=iot_platform
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
    depends_on:
      - zabbix-server
    ports:
      - 8081:8080
    volumes:
      - ./zbx_env/zabbix-web:/etc/ssl/nginx
    networks:
      - iot-server-net

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    environment:
      - ZBX_SERVER_HOST=zabbix-server
    depends_on:
      - zabbix-server
    ports:
      - 10050:10050
    volumes:
      - ./zbx_env/agent-logs:/var/log/zabbix
    networks:
      - iot-server-net